### ISSUE TITLE
Incorrect SUID description

### ISSUE THREAD

**Issue by mateuszstompor** [chlebik/rhcsa-practice-questions#15]
I've found it in your notes and decided to point it out (maybe you are not aware of the mistake?) 
> Istnieja specjalne privilage:
> * ​SUID ​(np. /usr/bin/passwd) -> ustawia sie u+s albo dajac prefix 4 - co oznacza, ze efektywny UID procesu, ktory ma dostep do pliku to UID ownera pliku. ​<b>Nie da sie tego ustawic na skryptach!!!</b>

Actually, SUID can be set only on regular files, below you've got an example that shows the usage and problem it solves
<br>
<img width="1162" alt="Screenshot 2021-03-26 at 22 04 48" src="https://user-images.githubusercontent.com/24464340/112692479-4e43f780-8e7f-11eb-9abc-560a995ff657.png">

Please do not treat my recent contributions and this issue as offence, I just want to share the knowledge :) Close once you acknowledge it

**Comment by chlebik** [comment]
So how is:  *​Nie da sie tego ustawic na skryptach!!!* not valid then? I mean, I'm all greatful for all the PRs/issues, I'm also for knowledge increase and share, but I don't know what's the exact point of this one ;)

**Comment by mateuszstompor** [comment]
I misunderstood your description and interpreted scripts as executables... I should have double-checked it before opening this up. Sorry for bothering you up this time
