### ISSUE TITLE
Question 008_create_users_with_specified_uid answer isn't correct

### ISSUE THREAD

**Issue by rediz** [chlebik/rhcsa-practice-questions#2]
Hello,

Iv been looking around ways to prepare and do all kinds of materias for rhcsa test.
Now that I tried to do and replicate the answer in 008 it doesn't work. I'll get error saying: "passwd -e 2020-11-19 davis
passwd: Only one user name may be specified."

Im not sure if something is changed or what, but that isn't working anymore. I can use it just "passwd -e john" but then the account expires right now. What I found out is the chage -command can be used like "chage davis" and it will ask what date's I want to set. Also its possible to say "chage -E 2020-11-19 davis" which is closest I find what your answer says.

- Rediz

**Comment by chlebik** [comment]
Yeah, I've checked it and surprisingly it does not work. Don't know how this happened but thank You for the comment.
