### ISSUE TITLE
bash vdo command not found

### ISSUE THREAD

**Issue by bartbus7** [chlebik/rhcsa-practice-questions#21]
While trying to install vdo, I got error bash: vdo command not found. Nor was stratisd recognized.

**Comment by chlebik** [comment]
I'm not in the subject that much anbymore but if it's not installed isn't it just a simple `yum install vdo`?

**Comment by bartbus7** [comment]
The error came from yum install vdo, and yum install kmod-kvdo, and also tried using dnf.

**Comment by bartbus7** [comment]
If rpm -q vdo kmod-kvdo shows nothing, and 
yum install vdo kmod-kvdo (or dnf/yum install kmod-kvdo vdo, or kmod-kvdo, or vdo) produce error bash: vdo command not found or vdo command unknown, on RHEL 8, then I don't know of any other way to get VDO on a machine.

**Comment by chlebik** [comment]
Hmm, my notes are mostly about RHEL7, RHEL8 certification appeared a couple of weeks after I've done the notes. In general AFAIK RHEL8 repos/software model changed in some way recently, probably that's the case.

**Comment by bartbus7** [comment]
No problem. I'm still researching, but coming up empty. I reached out to RH, but they were no help. It's on the exam.

**Comment by zctan95** [comment]
you should be able to install via yum or dnf
dnf install kmod-kvdo vdo -y
dnf install stratisd stratis-cli -y

Could try enabling and starting both services
systemctl enable --now stratisd
systemctl enable --now vdo

**Comment by bartbus7** [comment]
I tried those during my exam and they didn't work, but I think it can be done using lvcreate --type vdo -L ####M vgname, with #### being the size in MB and vgname being your volume group. I can't find any other way to create VDO other than these 2 ways. Pretty tricky on RH's part. In my RH course and book you are taught to use the command: dnf install kmod-kvdo vdo -ythen vdo create --name=vdoname --device=/dev/sdc --vdoLogicalSize=1T.......If there are more than these 2 ways to create a VDO, I haven't found them.

Les Lambus 

    On Tuesday, May 4, 2021, 7:43:09 AM CDT, Zcheng1995 ***@***.***> wrote:  
 
 


you should be able to install via yum or dnf
dnf install kmod-kvdo vdo -y
dnf install stratisd stratis-cli -y

Could try enabling and starting both services
systemctl enable --now stratisd
systemctl enable --now vdo

**Comment by zctan95** [comment]
Hmm that's strange, because vdo create is what redhat academy went along with:

Create the VDO volume vdo1, using the /dev/vdd device. Set its logical size to 50GB.

Switch to the root user.

[student@servera ~]$ sudo -i
[sudo] password for student: student
[root@servera ~]# 
Confirm that the vdo package is installed using the rpm command.

[root@servera ~]# yum list installed vdo
vdo-6.2.0.293-10.el8.x86_64
Create the vdo1 volume using the vdo create command.

[root@servera ~]# vdo create --name=vdo1 --device=/dev/vdd --vdoLogicalSize=50G
...output omitted...
Verify the availability of the vdo1 volume using the vdo list command.

[root@servera ~]# vdo list
vdo1

> I tried those during my exam and they didn't work, but I think it can be done using lvcreate --type vdo -L ####M vgname, with #### being the size in MB and vgname being your volume group. I can't find any other way to create VDO other than these 2 ways. Pretty tricky on RH's part. In my RH course and book you are taught to use the command: dnf install kmod-kvdo vdo -ythen vdo create --name=vdoname --device=/dev/sdc --vdoLogicalSize=1T.......If there are more than these 2 ways to create a VDO, I haven't found them. Les Lambus On Tuesday, May 4, 2021, 7:43:09 AM CDT, Zcheng1995 ***@***.***> wrote: you should be able to install via yum or dnf dnf install kmod-kvdo vdo -y dnf install stratisd stratis-cli -y Could try enabling and starting both services systemctl enable --now stratisd systemctl enable --now vdo — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by bartbus7** [comment]
That's exactly what I was taught also. I found the lvcreate way buried on their website and also other websites. I've Googled ways to create vdo for over a month and finally found the other one. it is very odd. I wish others would comment on it. 
Les Lambus 

    On Wednesday, May 5, 2021, 03:29:02 AM CDT, Zcheng1995 ***@***.***> wrote:  
 
 


Hmm that's strange, because vdo create is what redhat academy went along with:

Create the VDO volume vdo1, using the /dev/vdd device. Set its logical size to 50GB.

Switch to the root user.

***@***.*** ~]$ sudo -i
[sudo] password for student: student
***@***.*** ~]#
Confirm that the vdo package is installed using the rpm command.

***@***.*** ~]# yum list installed vdo
vdo-6.2.0.293-10.el8.x86_64
Create the vdo1 volume using the vdo create command.

***@***.*** ~]# vdo create --name=vdo1 --device=/dev/vdd --vdoLogicalSize=50G
...output omitted...
Verify the availability of the vdo1 volume using the vdo list command.

***@***.*** ~]# vdo list
vdo1


I tried those during my exam and they didn't work, but I think it can be done using lvcreate --type vdo -L ####M vgname, with #### being the size in MB and vgname being your volume group. I can't find any other way to create VDO other than these 2 ways. Pretty tricky on RH's part. In my RH course and book you are taught to use the command: dnf install kmod-kvdo vdo -ythen vdo create --name=vdoname --device=/dev/sdc --vdoLogicalSize=1T.......If there are more than these 2 ways to create a VDO, I haven't found them. Les Lambus On Tuesday, May 4, 2021, 7:43:09 AM CDT, Zcheng1995 @.***> wrote: you should be able to install via yum or dnf dnf install kmod-kvdo vdo -y dnf install stratisd stratis-cli -y Could try enabling and starting both services systemctl enable --now stratisd systemctl enable --now vdo — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.
