### ISSUE TITLE
When creating a user and password, wouldn't it be better to do a one-liner with useradd with -p <password>?

### ISSUE THREAD

**Issue by danmanrana** [chlebik/rhcsa-practice-questions#23]
And can an account expiration be done with usermod -e <date> instead of chage?

**Comment by chlebik** [comment]
Hmmm, the concept of 'better' here is fluid - the thing is to achieve the goal, no matter the way.

Ps. Sorry for the late answer, for some reasons I wasn't informed about this via email.
