### ISSUE TITLE
"008_create_users_with_specified_uid" - Question says to change "account validity", solution expires the password

### ISSUE THREAD

**Issue by littlefrank90** [chlebik/rhcsa-practice-questions#33]
It says right there:
"Remember there is a difference between password expiration and account validation. It is usually better to expire password and make user not being able to log into the system or disable the user, rather than deleting it."
So I don't get it, chage is supposed to just change password validity, right? Which is not what the question is asking.
So the given solution would not be the same as:
usermod --expiredate $(whatever the required date)

I'm confused.

**Comment by chlebik** [comment]
Thank you for creating this issue. Yup, it makes sense - I've changed the question.
