### ISSUE TITLE
001_restore_root_password.md - use .autorelabel in order to handle selinux when re-rooting box

### ISSUE THREAD

**Issue by jayhowell** [chlebik/rhcsa-practice-questions#4]
Instead of having to do...
```
In order to finish the task SELinux must be taken care of. If not, contents of /etc/shadow will be messed up. 
There are two commands to be provided:
 load_policy -i 
 chcon -t shadow_t /etc/shadow
```

You can just do
`touch /.autorelabel`
After you set the password.

And then reboot.  That will take care of relabeling for selinux.

**Comment by jayhowell** [comment]
Ah I see that Billy had already fixed this in his pull request.  https://github.com/chlebik/rhcsa-practice-questions/pull/3/commits/57816db595048618a9c37b5b7b2652abc67dca8b

**Comment by chlebik** [comment]
Merged and fixed
