### ISSUE TITLE
Solution is NOT the Correct one for 031_finding_files.md

### ISSUE THREAD

**Issue by aashishrbhandari** [chlebik/rhcsa-practice-questions#6]
Hello Chlebik,

> *Correct me if i am Wrong*

But the I Think the answer is not Correct for 
#### Question: Find **All Files** in /etc (not subdirectories) that where modified more than 180 days ago.

The Correct Answer Should be (Since it Says Files)
```find /etc -type f -maxdepth 1 -mtime +180```

If we use this:
```find /etc/ -maxdepth 1 -mtime +180```

It also gives dir
/etc/rc3.d
/etc/rc4.d
/etc/rc5.d
/etc/rc6.d

**Comment by chlebik** [comment]
Applied
